server:
  port: 1111 # HTTP Port (Tomcat) - by default Eureka runs on port 8761

#Configure the Eureka Server
eureka:
  instance:
    hostame: localhost
  client: # Not a Client, don't register itself
    registerWithEureka: false
    fetchRegistry: false

